import React from 'react';
import { Link } from 'react-router-dom';

const TermsPage: React.FC = () => {
  return (
    <div style={{
      maxWidth: '800px',
      margin: '0 auto',
      padding: '60px 20px',
      fontFamily: 'var(--sys-font-body-text-regular-font-family)',
      color: 'var(--sys-color-neutral-10)',
      lineHeight: '1.6'
    }}>
      <div style={{ marginBottom: '40px' }}>
        <Link to="/" style={{ color: 'var(--sys-color-primary-40)', textDecoration: 'none', fontWeight: 500 }}>
          &larr; Back to Home
        </Link>
      </div>

      <h1 style={{ fontSize: '2.5rem', marginBottom: '10px' }}>Terms of Service</h1>
      <p style={{ color: 'var(--sys-color-neutral-60)', marginBottom: '40px' }}>Last Updated: August 13, 2026</p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '30px' }}>
        <section>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '15px' }}>1. Acceptance of Terms</h2>
          <p>
            By accessing and using ContentSplit.ai, you accept and agree to be bound by the terms and provision of this agreement. 
            If you do not agree to abide by these terms, please do not use this service.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '15px' }}>2. Use of Service</h2>
          <p>
            ContentSplit.ai is an AI-powered content repurposing tool. You agree to use the service only for lawful purposes. 
            You must not use the service to generate content that is illegal, abusive, harassing, defamatory, or infringes on the intellectual property rights of others.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '15px' }}>3. AI Generated Content</h2>
          <p>
            The content generated by our service is provided by artificial intelligence. While we strive for high quality, we do not guarantee the accuracy, reliability, or appropriateness of generated content. 
            You are solely responsible for reviewing and validating any content before publishing it to your social media or other platforms.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '15px' }}>4. Subscriptions and Payments</h2>
          <p>
            Certain features of ContentSplit.ai require a paid subscription. Payments are billed in advance on a recurring basis as per your selected plan. 
            You may cancel your subscription at any time. Refunds are handled on a case-by-case basis according to our refund policy.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '15px' }}>5. Third-Party Accounts</h2>
          <p>
            You are responsible for maintaining the security of the third-party accounts (e.g., X, Facebook, LinkedIn) that you connect to our service. 
            We are not liable for any unauthorized access or actions taken on those accounts through our platform if such access stems from your failure to safeguard your credentials.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '15px' }}>6. Termination</h2>
          <p>
            We reserve the right to terminate or suspend access to our service immediately, without prior notice or liability, for any reason whatsoever, including, without limitation, if you breach the Terms of Service.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsPage;
